name: Interaction-API
version: '${project.version}'
main: me.ikevoodoo.interactionapi.InteractionApi
api-version: 1.17
load: POSTWORLD
authors: [ IkeVoodoo ]
description: Listen for player interaction
